version: '3'

services:
  api:
    image: node:16.20.2
    working_dir: /api-rest
    volumes:
      - .:/api-rest
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start "
 #command: sh -c "npm install && npm install -g pm2 && pm2-runtime start server.js"

